Construction/Controllers/AlbanilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Construction;

namespace Construction.Controllers
{
    public class AlbanilesController : Controller
    {
        private DB_CONSTRUCTIONEntities db = new DB_CONSTRUCTIONEntities();

        // GET: Albaniles
        public ActionResult Index()
        {
            return View(db.Albaniles.ToList());
        }

        // GET: Albaniles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Albaniles albaniles = db.Albaniles.Find(id);
            if (albaniles == null)
            {
                return HttpNotFound();
            }
            return View(albaniles);
        }

        // GET: Albaniles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Albaniles/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codigoAl,nombreCompleto,foto,ciudad,domicilio,aniosExpe,telefono,correo")] Albaniles albaniles)
        {
            if (ModelState.IsValid)
            {
                db.Albaniles.Add(albaniles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(albaniles);
        }

        // GET: Albaniles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Albaniles albaniles = db.Albaniles.Find(id);
            if (albaniles == null)
            {
                return HttpNotFound();
            }
            return View(albaniles);
        }

        // POST: Albaniles/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codigoAl,nombreCompleto,foto,ciudad,domicilio,aniosExpe,telefono,correo")] Albaniles albaniles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(albaniles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(albaniles);
        }

        // GET: Albaniles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Albaniles albaniles = db.Albaniles.Find(id);
            if (albaniles == null)
            {
                return HttpNotFound();
            }
            return View(albaniles);
        }

        // POST: Albaniles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Albaniles albaniles = db.Albaniles.Find(id);
            db.Albaniles.Remove(albaniles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Construction/Controllers/ContratistasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Construction;
using Rotativa;
namespace Construction.Controllers
{
    public class ContratistasController : Controller
    {
        private DB_CONSTRUCTIONEntities db = new DB_CONSTRUCTIONEntities();

        // GET: Contratistas
        public ActionResult Index()
        {
            return View(db.Contratistas.ToList());
        }

        public ActionResult Print()
        {
            return new ActionAsPdf("Index")
            { FileName = "MiPrueba.pdf" };
        }

        // GET: Contratistas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contratistas contratistas = db.Contratistas.Find(id);
            if (contratistas == null)
            {
                return HttpNotFound();
            }
            return View(contratistas);
        }

        // GET: Contratistas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contratistas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codigoC,nombreCompleto,foto,ciudad,domicilio,telefono,correo")] Contratistas contratistas)
        {
            if (ModelState.IsValid)
            {
                db.Contratistas.Add(contratistas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contratistas);
        }

        // GET: Contratistas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contratistas contratistas = db.Contratistas.Find(id);
            if (contratistas == null)
            {
                return HttpNotFound();
            }
            return View(contratistas);
        }

        // POST: Contratistas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codigoC,nombreCompleto,foto,ciudad,domicilio,telefono,correo")] Contratistas contratistas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contratistas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contratistas);
        }

        // GET: Contratistas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contratistas contratistas = db.Contratistas.Find(id);
            if (contratistas == null)
            {
                return HttpNotFound();
            }
            return View(contratistas);
        }

        // POST: Contratistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contratistas contratistas = db.Contratistas.Find(id);
            db.Contratistas.Remove(contratistas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Construction/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Construction.com</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mi cuenta <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Ver mi perfil", "Details/1", "Contratistas")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Ver mis contratos", "Index", "Contratistas")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Arquitectos", "Index", "Arquitectos")</li>
                    <li>@Html.ActionLink("Albañiles", "Index", "Albaniles")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Construction.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>